---
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
env:
  matrix:
    - ANSIBLE_VERSION="2.3"
    - ANSIBLE_VERSION="2.9"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible=="$ANSIBLE_VERSION" molecule[docker]
script:
  - molecule test
