# file: python/tasks/pip.yml

- name: python | pip | Install pip for python2
  apt:
    name: python-pip
  when: python_source_version | int == 2

- name: python | pip | Install pip for python3
  apt:
    name: python3-pip
  when: python_source_version | int == 3

- name: python | pip | update setuptools
  pip:
    name: "setuptools{% if python_setuptools_version is defined %}=={{python_setuptools_version}}{% endif %}"
    state: present
