# file: python/tasks/python.yml

- name: Install gnupg
  apt:
    name: gnupg
    state: present
  become: true
  become_user: root
  when: python_apt_ppa is defined

- name: Add Python PPA
  apt_repository:
    repo: "{{ python_apt_ppa }}"
    state: present
  become: true
  become_user: root
  when: python_apt_ppa is defined

- name: Update apt cache
  apt:
    update_cache: "yes"

- name: python | Install python packages
  apt:
    pkg: "{{ python_packages }}"
    state: present