---
dependency:
  name: galaxy
driver:
  name: docker
lint: yamllint .
platforms:
  - name: python3-ubuntu-1804
    image: ubuntu:18.04
    privileged: true
    command: /sbin/init
  - name: python3-ubuntu-2004
    image: ubuntu:20.04
    privileged: true
    command: /sbin/init
  - name: python3-ubuntu-2203
    image: ubuntu:22.04
    privileged: true
    command: /sbin/init
  - name: python3-ubuntu-latest
    image: ubuntu:latest
    privileged: true
    command: /sbin/init
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
provisioner:
  name: ansible
  lint: ansible-lint
verifier:
  name: testinfra
  lint: flake8
